#!/usr/bin/env python
"""
RSMeans API helper for the door_enhancement measure.

This module is intentionally self-contained and local to door_enhancement.
It handles all RSMeans cost lookups for door components: whole doors, bottom
seals (brush weatherstrip, automatic door bottom, silicone smoke gasket), and
top/side seals (jamb weatherstrip, silicone smoke gasket).

This script can also be used as a standalone CLI tool to query RSMeans costs
from a saved OSM file (run ``python resources/call_rsmeans_api.py --help``).

Search behaviour (three-tier lookup):
1. If the caller provides an explicit RSMeans unit costline ID, that ID is
   resolved first via a direct catalog lookup before falling back to search.
2. A text search is attempted using progressive alternative terms generated by
   ``generate_search_term_alternatives``.  If the best candidate's clamped
   score is >= ``MIN_ACCEPTABLE_MATCH_SCORE`` (70.0), that candidate is used.
3. If no search succeeds or the score is too low, a hard-coded fallback ID
   from ``DOOR_FALLBACK_RSMEANS_IDS`` is resolved directly by catalog lookup.
"""

import argparse
import importlib.util
import json
import os
import re
import sys
from pathlib import Path
from typing import Optional, Dict, Any, List

import requests
import urllib3
from dotenv import load_dotenv

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


_AUXILIARY_UTILS_DIR = Path(__file__).resolve().parents[3] / "parametric_run" / "auxiliary"
if str(_AUXILIARY_UTILS_DIR) not in sys.path:
    sys.path.insert(0, str(_AUXILIARY_UTILS_DIR))

_LOGGING_MODULE_PATH = _AUXILIARY_UTILS_DIR / "rsmeans_logging.py"
_LOGGING_SPEC = importlib.util.spec_from_file_location("door_rsmeans_logging", _LOGGING_MODULE_PATH)
_LOGGING_MODULE = importlib.util.module_from_spec(_LOGGING_SPEC)
_LOGGING_SPEC.loader.exec_module(_LOGGING_MODULE)
append_measure_raw_record = _LOGGING_MODULE.append_measure_raw_record
append_measure_summary_record = _LOGGING_MODULE.append_measure_summary_record


DEFAULT_FEATURE_KEYS = {
    "name": "retrofit_material_name",
    "description": "retrofit_material_description",
    "quantity": "retrofit_material_quantity",
    "unit": "retrofit_material_unit",
    "division_code": "rsmeans_division_code",
    "unit_cost": "rsmeans_unit_cost",
    "total_cost": "rsmeans_total_cost",
}


# --- Unit-of-measure (UOM) compatibility checking -------------------------
# RSMeans returns ``unitOfMeasure`` strings such as "L.F.", "S.F.", "C.Y.",
# "Ea.", "Opng" with inconsistent punctuation/casing. The requested material
# ``unit`` is one of "LF", "SF", "CF", "CY", "EA". Multiplying a per-Opng
# cost by an LF quantity (or vice versa) silently produces wildly wrong
# totals, so every cost-line we consume must be UOM-checked before use.
_UOM_NORMALIZE = {
    "lf": "LF", "l.f.": "LF", "linear foot": "LF", "linear feet": "LF",
    "sf": "SF", "s.f.": "SF", "square foot": "SF", "square feet": "SF",
    "cf": "CF", "c.f.": "CF", "cubic foot": "CF", "cubic feet": "CF",
    "cy": "CY", "c.y.": "CY", "cubic yard": "CY", "cubic yards": "CY",
    "ea": "EA", "ea.": "EA", "each": "EA",
    "opng": "OPNG", "opening": "OPNG",
    "lb": "LB", "lb.": "LB", "pound": "LB",
    "set": "SET",
    "job": "JOB",
}


def _normalize_uom(uom: Any) -> str:
    """Normalize an RSMeans unitOfMeasure string to a canonical token."""
    if uom is None:
        return ""
    text = str(uom).strip().lower()
    if not text:
        return ""
    return _UOM_NORMALIZE.get(text, text.upper().replace(".", "").replace(" ", ""))


def _uom_compatible(requested_unit: Any, returned_uom: Any) -> bool:
    """Return True if a cost-line priced in ``returned_uom`` can be safely
    multiplied by a quantity expressed in ``requested_unit``.

    Compatibility rules:
    - Empty / unknown returned UOM -> treated as compatible (best-effort,
      preserves existing behaviour for older API responses).
    - Empty requested unit -> treated as compatible.
    - Otherwise: tokens must match after normalization. EA and OPNG are
      treated as interchangeable (a "per opening" door price is acceptable
      for a per-each door quantity).
    """
    req = _normalize_uom(requested_unit)
    ret = _normalize_uom(returned_uom)
    if not ret or not req:
        return True
    if req == ret:
        return True
    interchangeable = {"EA", "OPNG"}
    if req in interchangeable and ret in interchangeable:
        return True
    return False


DOOR_FALLBACK_RSMEANS_IDS = {
    # Door sealing components (from EC3 Query Strings sheet).
    "silicone adhesive smoke gasket": "087125105050",
    "brush weatherstrip": "087125103700",
    "automatic door bottom": "087125103650",
    # Per EC3 Query Strings spreadsheet (RSMeans sheet): jamb weatherstripping
    # uses costline 083323104000 (door rolling service, extruded rubber jambs).
    "jamb weatherstrip": "083323104000",
    "jamb weatherstripping": "083323104000",
    # Whole door components (from EC3 Query Strings sheet).
    "wood door leaf": "081416090025",
    "wooden door": "081416090025",
    "garage door": "083613200200",
    "commercial glass door system": "083213100450",
    # Compatibility alias for legacy naming.
    "window door system": "083213100450",
    "glass door": "083213100450",
    "polystyrene core steel door": "081313130020",
    "polyurethane core steel door": "081313130020",
    "honeycomb core steel door": "081313130020",
    "stiffened core steel door": "081313130020",
    "stiffened core": "081313130020",
}

# Forced fallback IDs requested for specific door/seal options.
# Priority is still: user-provided explicit ID > forced fallback ID > search.
FORCED_RSMEANS_IDS = {
    "silicone adhesive smoke gasket": "087125105050",
    "brush weatherstrip": "087125103700",
    "automatic door bottom": "087125103650",
    "jamb weatherstrip": "083323104000",
    "jamb weatherstripping": "083323104000",
    "wooden door": "081416090025",
    "garage door": "083613200200",
    "glass door": "083213100450",
    "polystyrene core steel door": "081313130020",
    "polyurethane core steel door": "081313130020",
    "honeycomb core steel door": "081313130020",
    "stiffened core steel door": "081313130020",
}

# Minimum clamped match score [0-100] required to accept a search result.
# Scores below this trigger the fallback costline-ID lookup so that a
# low-confidence text match never silently produces wrong costs.
# Raised from 50 -> 70 because at 50 unrelated lines (e.g. a stainless-steel
# glass door costline) were scoring high enough to be accepted for a
# "wooden door" request, producing dramatically wrong costs (~$70k).
# Curated fallback IDs in DOOR_FALLBACK_RSMEANS_IDS are reliable, so it is
# safer to fall through to them when the search match is weak.
MIN_ACCEPTABLE_MATCH_SCORE = 70.0

RSMEANS_RAW_LOG_ENV = "RSMEANS_SCENARIO_RAW_LOG_PATH"
MEASURE_LOG_SLUG = "door_enhancement"


def _append_rsmeans_raw_log(material, matched_item, catalog, match_type, search_term):
    """Append raw RSMeans unit-cost fields for the matched line item."""
    if not isinstance(matched_item, dict):
        return
    append_measure_raw_record(MEASURE_LOG_SLUG, material, matched_item, catalog, match_type, search_term)


def _id_matches_division(item_id: Any, division_code: Any) -> bool:
    """Return True if ``item_id`` (an RSMeans line number like '087125103700')
    starts with ``division_code`` (e.g. '08', '0871'). Empty division means
    no constraint. Used as a defense-in-depth check to ensure a door-related
    lookup never accepts a stray match in an unrelated MasterFormat
    division (e.g. concrete sealants under 0701).
    """
    if not division_code:
        return True
    if not item_id:
        return False
    return str(item_id).strip().startswith(str(division_code).strip())


def _get_feature_as_string(props, feature_name: str) -> Optional[str]:
    if not props.hasFeature(feature_name):
        return None
    value_str = props.getFeatureAsString(feature_name)
    if value_str.is_initialized():
        return value_str.get()
    value_double = props.getFeatureAsDouble(feature_name)
    if value_double.is_initialized():
        return str(value_double.get())
    value_int = props.getFeatureAsInteger(feature_name)
    if value_int.is_initialized():
        return str(value_int.get())
    return None


def _get_feature_as_float(props, feature_name: str) -> Optional[float]:
    if not props.hasFeature(feature_name):
        return None
    value_double = props.getFeatureAsDouble(feature_name)
    if value_double.is_initialized():
        return float(value_double.get())
    value_int = props.getFeatureAsInteger(feature_name)
    if value_int.is_initialized():
        return float(value_int.get())
    value_str = props.getFeatureAsString(feature_name)
    if value_str.is_initialized():
        try:
            return float(value_str.get())
        except ValueError:
            return None
    return None


def _extract_search_items(search_results: Dict[str, Any]) -> List[Dict[str, Any]]:
    if not search_results:
        return []
    items = search_results.get("items")
    if isinstance(items, list):
        return items
    return search_results.get("unitLines", {}).get("items", [])


def _filter_demo_items(items: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Reject demolition / removal cost-lines.

    Excludes any item that:
    - has an ``id`` starting with ``0805`` (MasterFormat Demolition for
      Openings), or
    - whose description mentions demolition / demo / remove (without an
      "and replace" qualifier).

    Important: returns an empty list if everything was filtered out, so the
    caller can fall through to other catalogs / fallback IDs instead of
    silently accepting a demolition match.
    """
    filtered = []
    for item in items:
        item_id = str(item.get("id", "")).strip()
        if item_id.startswith("0805"):
            continue
        description = str(item.get("description", "")).lower()
        if "demolition" in description:
            continue
        if re.search(r"\bremove\b", description) and "replace" not in description:
            continue
        if re.search(r"\bdemo\b", description):
            continue
        filtered.append(item)
    return filtered


def _normalize_search_text(text: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", " ", str(text).lower())
    return re.sub(r"\s+", " ", cleaned).strip()


def _tokenize_search_text(text: str) -> set:
    tokens = _normalize_search_text(text).split()
    return {tok for tok in tokens if len(tok) > 2}


def _score_rsmeans_candidate(material_name: str, item: Dict[str, Any]) -> float:
    """Score a single RSMeans candidate item against a material name.

    Scoring rules (additive):
    - +60  if the normalised material name is a substring of the description
    - +12 per overlapping token (words > 2 chars)
    - +10 if both material and description contain "door"
    - -20 if description contains fastener/clip/anchor/hanger keywords
    - +0..1 bonus proportional to description length (up to 120 chars)

    Returns:
        Raw score (unbounded; negative values indicate a very poor match).
        The caller clamps this to [0, 100] before comparing to the threshold.
    """
    description = str(item.get("description", ""))
    if not description:
        return -1.0

    material_norm = _normalize_search_text(material_name)
    description_norm = _normalize_search_text(description)
    material_tokens = _tokenize_search_text(material_name)
    description_tokens = _tokenize_search_text(description)

    score = 0.0
    if material_norm and material_norm in description_norm:
        score += 60.0

    token_overlap = material_tokens.intersection(description_tokens)
    score += 12.0 * len(token_overlap)

    # Prefer door entries for door materials.
    if "door" in material_norm and "door" in description_norm:
        score += 10.0

    # Penalize likely accessory lines over assembly lines.
    if any(tok in description_norm for tok in ["fastener", "clip", "anchor", "hanger"]):
        score -= 20.0

    score += min(len(description_norm), 120) / 120.0
    return score


def _select_best_rsmeans_candidate(
    material_name: str,
    items: List[Dict[str, Any]],
    material: Optional[Dict[str, Any]] = None,
) -> tuple:
    """Select the best-scoring RSMeans candidate from a list of search results.

    Each item is scored by ``_score_rsmeans_candidate`` then clamped to
    [0, 100].  If the top clamped score is below ``MIN_ACCEPTABLE_MATCH_SCORE``
    the function attempts a fallback hard-coded ID via
    ``_get_default_fallback_rsmeans_id`` and returns that instead.

    Args:
        material_name: Human-readable material name used for scoring.
        items: Raw RSMeans search result items.
        material: Full material dict (used to pass description to fallback).

    Returns:
        (best_item_or_fallback_dict, scored_list)  where ``scored_list``
        contains all candidates with their scores for diagnostic logging.
    """
    if not items:
        return None, []

    scored = []
    for idx, item in enumerate(items):
        raw_score = _score_rsmeans_candidate(material_name, item)
        bounded_score = max(0.0, min(100.0, raw_score))
        scored.append({
            "index": idx,
            "rsmeans_id": item.get("id", "unknown"),
            "description": str(item.get("description", ""))[:100],
            "score": round(bounded_score, 2),
            "raw_score": round(raw_score, 2),
        })

    scored.sort(key=lambda x: -x["score"])
    top_score = scored[0].get("score", 0.0)  # already clamped to [0, 100]
    # If the best clamped score is below the acceptance threshold, skip this
    # match entirely and fall back to a known-good hard-coded costline ID.
    if top_score < MIN_ACCEPTABLE_MATCH_SCORE:
        fallback_id = _get_default_fallback_rsmeans_id(
            material_name,
            (material or {}).get("description", ""),
        )
        if fallback_id:
            return {
                "id": fallback_id,
                "description": f"[fallback costline] {material_name}",
                "is_fallback": True,
                "fallback_reason": (
                    f"poor_match_score_fallback:{top_score:.1f}"
                    f"<{MIN_ACCEPTABLE_MATCH_SCORE}"
                ),
            }, scored

    best_idx = scored[0]["index"]
    best_candidate = items[best_idx]
    return best_candidate, scored


def _extract_bare_components(item: Dict[str, Any]) -> Dict[str, Any]:
    """Pull material/labor/equipment unit costs (Including O&P) from a RSMeans line item.

    The RSMeans API returns both bare (no overhead/profit) and "Op" (already
    including the published O&P markups) variants of the material, labor and
    equipment components. To match the book's published "Total Incl. O&P"
    figure exactly, this helper extracts the ``*OpCost`` fields so the
    per-line sum equals ``totalOpCost`` (no additional markup needed).

    If the response is missing the ``*OpCost`` breakdown, the helper falls
    back to attributing the entire ``totalOpCost`` value to ``material`` so
    upstream callers degrade gracefully. The ``source`` field flags which
    branch was taken. The function name is kept for backward compatibility.
    """
    lc = item.get("localizedCosts", {}) or {}
    if any(k in lc for k in ("materialOpCost", "laborOpCost", "equipmentOpCost")):
        return {
            "material": float(lc.get("materialOpCost", 0.0) or 0.0),
            "labor": float(lc.get("laborOpCost", 0.0) or 0.0),
            "equipment": float(lc.get("equipmentOpCost", 0.0) or 0.0),
            "source": "op_components",
        }
    return {
        "material": float(lc.get("totalOpCost", 0.0) or 0.0),
        "labor": 0.0,
        "equipment": 0.0,
        "source": "total_op_cost_fallback",
    }


def _split_total_by_bare(item: Dict[str, Any], total: float) -> Dict[str, Any]:
    """Split a project total cost into material/labor/equipment components
    using the per-component O&P fractions from the RSMeans line item.

    Note: ``total`` is the project-level cost computed using the per-line
    ``totalOpCost`` and therefore already includes RSMeans' published O&P.
    No additional overhead/profit markup should be layered on top.
    """
    bare = _extract_bare_components(item)
    bare_unit = bare["material"] + bare["labor"] + bare["equipment"]
    if bare_unit > 0:
        return {
            "material": total * (bare["material"] / bare_unit),
            "labor": total * (bare["labor"] / bare_unit),
            "equipment": total * (bare["equipment"] / bare_unit),
            "source": bare["source"],
        }
    return {"material": total, "labor": 0.0, "equipment": 0.0, "source": bare["source"]}


def _normalize_text(value: str) -> str:
    return re.sub(r"\s+", " ", str(value or "").lower()).strip()


def _get_forced_fallback_rsmeans_id(material_name: str, material_description: str = "") -> Optional[str]:
    """Return a forced fallback ID for configured seal/door materials.

    Only applies to specific materials listed in FORCED_RSMEANS_IDS.
    """
    normalized = _normalize_text(f"{material_name or ''} {material_description or ''}")
    for phrase in sorted(FORCED_RSMEANS_IDS.keys(), key=len, reverse=True):
        if phrase in normalized:
            return FORCED_RSMEANS_IDS[phrase]
    return None


def _get_default_fallback_rsmeans_id(material_name: str, material_description: str = "") -> Optional[str]:
    """Return a hard-coded fallback RSMeans costline ID for known door materials.

    Lookup priority:
    1. Exact phrase match against ``DOOR_FALLBACK_RSMEANS_IDS`` keys.
    2. Keyword heuristics (garage door, weatherstrip, smoke gasket, steel door).
    3. Generic door fallback if nothing else matches.

    Returns ``None`` if the material cannot be mapped to any known ID.
    """
    text = f"{material_name or ''} {material_description or ''}"
    normalized = _normalize_text(text)

    # Exact phrase matching first.
    for phrase, rsmeans_id in DOOR_FALLBACK_RSMEANS_IDS.items():
        if phrase in normalized:
            return rsmeans_id

    # Keyword-based fallback for near matches.
    if "garage" in normalized and "door" in normalized:
        return DOOR_FALLBACK_RSMEANS_IDS["garage door"]
    if "weatherstrip" in normalized or "weatherstripping" in normalized:
        if "jamb" in normalized:
            return DOOR_FALLBACK_RSMEANS_IDS["jamb weatherstrip"]
        return DOOR_FALLBACK_RSMEANS_IDS["brush weatherstrip"]
    if "smoke" in normalized and ("gasket" in normalized or "seal" in normalized):
        return DOOR_FALLBACK_RSMEANS_IDS["silicone adhesive smoke gasket"]
    if "core" in normalized and "steel" in normalized and "door" in normalized:
        return DOOR_FALLBACK_RSMEANS_IDS["polystyrene core steel door"]
    if "door" in normalized:
        return DOOR_FALLBACK_RSMEANS_IDS["commercial glass door system"]

    return None


def _lookup_cost_item_by_rsmeans_id(
    client: "RSMeansAPIClient",
    rsmeans_id: str,
    catalog: str,
    release_id: str,
    location_id: str,
    labor_type: str,
    measurement_system: str,
) -> Optional[Dict[str, Any]]:
    cost_line = client.get_unit_costlines(
        release_id=release_id,
        catalog=catalog,
        location_id=location_id,
        labor_type=labor_type,
        measurement_system=measurement_system,
        division_code=rsmeans_id,
    )
    if not cost_line or "items" not in cost_line:
        return None

    items = cost_line["items"]
    # Exact match first.
    for item in items:
        if item.get("id") == rsmeans_id:
            return item

    # If the exact sub-line ID was not found (the catalogue may not carry that
    # specific 12-character variant), fall back to the first item in the same
    # section that has a positive cost.  This handles cases like requesting
    # "087125105050" when only "087125105000" is present in the catalogue.
    for item in items:
        if float(item.get("localizedCosts", {}).get("totalOpCost", 0.0)) > 0:
            return item
    return None


def generate_search_term_alternatives(material_name: str) -> List[tuple]:
    """Generate alternative search terms and RSMeans division codes for a material.

    Returns a list of ``(search_term, division_code)`` tuples in priority order.
    Callers should try each tuple until a result is found.

    Progressive fallback strategy:
    1. Original name with inferred division (Strategy 1)
    2. Dimension-stripped name (removes e.g. "3 ft 0 in x 7 ft 0 in")
    3. Domain-specific alternatives (door types, sealing products, insulation)
    4. Single-word simplification (last word, then first+last)
    5. Search without any division constraint as final fallback

    Example::

        generate_search_term_alternatives("polystyrene core steel door 3 ft 0 in x 7 ft 0 in")
        # -> [("polystyrene core steel door ...", "08"),
        #     ("polystyrene core steel door", "08"),
        #     ("metal door", "08"), ..., ("door", "08")]

    Args:
        material_name: Original material name (e.g., "steel door").

    Returns:
        List of ``(search_term, division_code)`` tuples to try in order.
    """
    alternatives = []
    name_lower = material_name.lower().strip()
    # Remove size tokens like "5 ft 3 in x 7 ft 7 in" to improve match rate
    cleaned_name = re.sub(r"\b\d+(?:\.\d+)?\b", "", name_lower)
    cleaned_name = cleaned_name.replace("ft", " ").replace("in", " ").replace("x", " ")
    cleaned_name = re.sub(r"\s+", " ", cleaned_name).strip()
    
    # Strategy 1: Original name with detected division
    original_division = get_division_from_material_type(material_name)
    alternatives.append((material_name, original_division))
    if cleaned_name and cleaned_name != name_lower:
        alternatives.append((cleaned_name, get_division_from_material_type(cleaned_name)))
    
    # Strategy 2: Door-specific alternatives
    if "door" in name_lower:
        if "metal" in name_lower or "steel" in name_lower:
            alternatives.append(("metal door", "08"))
        alternatives.extend([
            ("door replacement", "08"),
            ("door unit", "08"),
            ("door assembly", "08"),
            ("door", "08"),
        ])
    
    # Strategy 3: Insulation alternatives
    elif "insulation" in name_lower or "insul" in name_lower:
        alternatives.extend([
            ("wall insulation", "07"),
            ("roof insulation", "07"),
            ("batt insulation", "07"),
            ("rigid insulation", "07"),
            ("insulation", "07"),
        ])
    
    # Strategy 4: HVAC alternatives
    elif any(term in name_lower for term in ["hvac", "heat pump", "furnace", "boiler", "chiller"]):
        alternatives.extend([
            (material_name.replace("system", "unit"), "23"),
            (material_name.replace("equipment", "unit"), "23"),
            ("HVAC equipment", "23"),
        ])
    
    # Strategy 5: Try simplifying compound terms (remove adjectives/modifiers)
    words = cleaned_name.split() if cleaned_name else name_lower.split()
    if len(words) > 1:
        # Try just the last word (often the noun)
        last_word = words[-1]
        last_div = get_division_from_material_type(last_word)
        if (last_word, last_div) not in alternatives:
            alternatives.append((last_word, last_div))
        
        # Try first + last word
        if len(words) > 2:
            simplified = f"{words[0]} {words[-1]}"
            simp_div = get_division_from_material_type(simplified)
            if (simplified, simp_div) not in alternatives:
                alternatives.append((simplified, simp_div))
    
    # Strategy 6: Try without division constraint (let RSMeans search all divisions)
    if (material_name, None) not in alternatives:
        alternatives.append((material_name, None))
    
    return alternatives


def get_division_from_material_type(material_type: str) -> Optional[str]:
    mapping = {
        "concrete": "03",
        "footing": "03",
        "slab": "03",
        "brick": "04",
        "masonry": "04",
        "block": "04",
        "steel": "05",
        "metal": "05",
        "wood": "06",
        "lumber": "06",
        "insulation": "07",
        "roofing": "07",
        "waterproofing": "07",
        "sealant": "07",
        "door": "08",
        "window": "08",
        "glazing": "08",
        "glass": "08",
        "frame": "08",
        "sash": "08",
        "drywall": "09",
        "gypsum": "09",
        "paint": "09",
        "flooring": "09",
        "ceiling": "09",
        "tile": "09",
        "plumbing": "22",
        "pipe": "22",
        "hvac": "23",
        "duct": "23",
        "boiler": "23",
        "chiller": "23",
        "furnace": "23",
        "electrical": "26",
        "lighting": "26",
        "wiring": "26",
    }

    material_lower = material_type.lower().strip()
    if material_lower in mapping:
        return mapping[material_lower]

    for key, division in mapping.items():
        if key in material_lower or material_lower in key:
            return division
    return None


class RSMeansAPIClient:
    def __init__(self, client_id, client_secret, use_sandbox: bool = False):
        self.client_id = client_id
        self.client_secret = client_secret
        self.token_url = "https://login.gordian.com/connect/token"
        self.base_url = "https://dataapi-sb.gordian.com" if use_sandbox else "https://dataapi.gordian.com"
        self.access_token = None
        self.token_type = None

    def authenticate(self) -> bool:
        data = {
            "grant_type": "client_credentials",
            "client_id": self.client_id,
            "client_secret": self.client_secret,
            "scope": "rsm_api:costdata",
        }
        try:
            response = requests.post(self.token_url, data=data, verify=False)
            response.raise_for_status()
            token_data = response.json()
            self.access_token = token_data.get("access_token")
            self.token_type = token_data.get("token_type", "Bearer")
            print("Authentication successful!")
            return True
        except requests.exceptions.RequestException as e:
            print(f"Authentication failed: {e}")
            return False

    def _get_headers(self) -> Dict[str, str]:
        if not self.access_token:
            raise RuntimeError("Not authenticated. Call authenticate() first.")
        return {
            "Authorization": f"{self.token_type} {self.access_token}",
            "Content-Type": "application/json",
        }

    def search_unit_costlines(
        self,
        release_id: str,
        measurement_system: str,
        search_term: str,
        catalog: Optional[str] = "bc-mf",
        location_id: Optional[str] = "us-us-national",
        labor_type: Optional[str] = "std",
        division_code: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        catalog_id = f"{catalog}-{measurement_system}-{labor_type}-{release_id}-{location_id}"
        endpoint = f"{self.base_url}/v1/costdata/unit/catalogs/{catalog_id}/costlines/_search"
        params = {"searchTerm": search_term} if search_term else {}
        if division_code:
            params["divisionCode"] = division_code
        try:
            response = requests.get(endpoint, headers=self._get_headers(), params=params, verify=False)
            response.raise_for_status()
            print(
                f"Search: catalog={catalog_id}, division={division_code}, term={search_term}"
            )
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error retrieving unit cost line: {e}")
            return None

    def get_unit_costlines(
        self,
        release_id: str,
        measurement_system: str,
        division_code: str,
        catalog: str = "bc-mf",
        location_id: str = "us-us-national",
        labor_type: str = "std",
    ) -> Optional[Dict[str, Any]]:
        catalog_id = f"{catalog}-{measurement_system}-{labor_type}-{release_id}-{location_id}"
        endpoint = f"{self.base_url}/v1/costdata/unit/catalogs/{catalog_id}/costlines"
        params = {"divisionCode": division_code} if division_code else {}
        try:
            response = requests.get(endpoint, headers=self._get_headers(), params=params, verify=False)
            response.raise_for_status()
            print(f"Cost lines: catalog={catalog_id}, division={division_code}")
            return response.json()
        except requests.exceptions.RequestException as e:
            print(f"Error retrieving unit cost line: {e}")
            return None

    def search_materials_batch(
        self,
        materials: List[Dict[str, Any]],
        release_id: str = "2019-an",
        catalog: str = "bc-mf",
        location_id: str = "us-us-national",
        labor_type: str = "std",
        measurement_system: str = "imp",
        save_search_results_path: Optional[str] = None,
        skip_if_cost_present: bool = True,
    ) -> Dict[str, Any]:
        results = {
            "total_cost": 0.0,
            "materials": [],
            "errors": [],
            "search_log": [],
        }

        for material in materials:
            material_name = material.get("name", "")
            quantity = material.get("quantity", 1.0)
            division_hint = material.get("division_code")
            existing_unit_cost = material.get("unit_cost")
            existing_total_cost = material.get("total_cost")

            if not material_name:
                results["errors"].append("Material name is required")
                continue

            if skip_if_cost_present and existing_total_cost is not None:
                results["materials"].append({
                    **material,
                    "unit_cost": existing_unit_cost,
                    "total_cost": existing_total_cost,
                    "source": "additional_properties",
                })
                results["total_cost"] += float(existing_total_cost)
                continue

            # Generate alternative search terms
            search_alternatives = generate_search_term_alternatives(material_name)
            
            # If we have a division hint from material properties, prioritize it
            if division_hint:
                # Insert original name with provided division at the front
                search_alternatives.insert(0, (material_name, division_hint))
            
            search_results = None
            tried_terms = []
            
            # Try each alternative search term until we find a match
            for alt_term, alt_division in search_alternatives:
                tried_terms.append(f"{alt_term} (div:{alt_division or 'any'})")
                
                try:
                    search_results = self.search_unit_costlines(
                        release_id=release_id,
                        measurement_system=measurement_system,
                        search_term=alt_term,
                        catalog=catalog,
                        location_id=location_id,
                        labor_type=labor_type,
                        division_code=alt_division,
                    )
                    
                    items = _filter_demo_items(_extract_search_items(search_results))
                    if items:
                        if alt_term != material_name:
                            print(f"  -> Found match using alternative term: '{alt_term}'")
                        break
                except Exception as e:
                    continue
            
            items = _filter_demo_items(_extract_search_items(search_results))
            if not items:
                error_msg = f"No RSMeans match found for: {material_name}"
                if len(tried_terms) > 1:
                    error_msg += f" (tried {len(tried_terms)} alternatives)"
                results["errors"].append(error_msg)
                results["search_log"].append({
                    "material": material_name,
                    "tried_terms": tried_terms,
                    "result": "no_match"
                })
                continue
            
            try:

                first_item = items[0]
                division_code = first_item.get("id")
                item_description = first_item.get("description", material_name)

                if not division_code:
                    results["errors"].append(f"No division code found for: {material_name}")
                    continue

                cost_line = self.get_unit_costlines(
                    release_id=release_id,
                    catalog=catalog,
                    location_id=location_id,
                    labor_type=labor_type,
                    measurement_system=measurement_system,
                    division_code=division_code,
                )

                results["search_log"].append({
                    "material_name": material_name,
                    "division_hint": division_hint,
                    "search_results_count": len(items),
                    "division_code": division_code,
                    "first_match": first_item.get("description", ""),
                    "has_cost_data": cost_line is not None and "items" in cost_line,
                })

                if cost_line and "items" in cost_line:
                    for item in cost_line["items"]:
                        if item.get("id") == division_code:
                            unit_cost = item.get("localizedCosts", {}).get("totalOpCost", 0.0)
                            total_material_cost = unit_cost * quantity

                            results["materials"].append({
                                **material,
                                "description": item_description,
                                "division_code": division_code,
                                "unit_cost": unit_cost,
                                "total_cost": total_material_cost,
                                "source": "rsmeans_api",
                            })

                            results["total_cost"] += total_material_cost
                            break
                    else:
                        results["errors"].append(f"Division code not found in response: {division_code}")
                else:
                    results["errors"].append(f"No cost data returned for: {material_name}")

            except Exception as e:
                results["errors"].append(f"Error processing material '{material_name}': {str(e)}")

        if save_search_results_path:
            try:
                output_path = Path(save_search_results_path)
                output_path.parent.mkdir(parents=True, exist_ok=True)
                with open(output_path, "w", encoding="utf-8") as f:
                    json.dump(results, f, indent=2)
            except Exception as e:
                results["errors"].append(f"Could not save search results to JSON: {str(e)}")

        return results


def load_openstudio_model(model_path: Path):
    try:
        import openstudio  # pylint: disable=import-error
    except Exception as exc:
        raise RuntimeError("openstudio python bindings are required to read a model") from exc

    translator = openstudio.osversion.VersionTranslator()
    model_opt = translator.loadModel(openstudio.toPath(str(model_path)))
    if not model_opt.is_initialized():
        raise RuntimeError(f"Failed to load model: {model_path}")
    return model_opt.get()


def _format_feet_inches(value_m: float) -> str:
    inches_total = value_m * 39.37007874
    feet = int(inches_total // 12)
    inches = int(round(inches_total - feet * 12))
    if inches == 12:
        feet += 1
        inches = 0
    return f"{feet} ft {inches} in"


def _estimate_door_dimensions_m(subsurface) -> Optional[Dict[str, float]]:
    try:
        vertices = subsurface.vertices()
    except Exception:
        return None
    if not vertices or len(vertices) < 3:
        return None

    xs = [v.x() for v in vertices]
    ys = [v.y() for v in vertices]
    zs = [v.z() for v in vertices]

    dx = max(xs) - min(xs)
    dy = max(ys) - min(ys)
    dz = max(zs) - min(zs)

    width_m = max(dx, dy)
    height_m = dz if dz > 0 else min(dx, dy)
    if width_m <= 0 or height_m <= 0:
        return None
    return {"width_m": width_m, "height_m": height_m}


def _get_default_exterior_door_construction(model):
    try:
        building = model.getBuilding()
        dcs_opt = building.defaultConstructionSet()
        if not dcs_opt.is_initialized():
            return None
        dcs = dcs_opt.get()
        ext_subs_opt = dcs.defaultExteriorSubSurfaceConstructions()
        if not ext_subs_opt.is_initialized():
            return None
        ext_subs = ext_subs_opt.get()
        door_opt = ext_subs.doorConstruction()
        if door_opt.is_initialized():
            return door_opt.get()
    except Exception:
        return None
    return None


def _collect_material_keywords_from_construction(construction) -> List[str]:
    keywords = set()
    try:
        if construction.to_LayeredConstruction().is_initialized():
            lc = construction.to_LayeredConstruction().get()
            layers = lc.layers()
        else:
            layers = []
    except Exception:
        layers = []

    for layer in layers:
        try:
            name = layer.nameString().lower()
        except Exception:
            name = ""
        if "metal" in name or "steel" in name:
            keywords.add("metal")
        if "aluminum" in name or "aluminium" in name:
            keywords.add("aluminum")
        if "insulation" in name or "insul" in name:
            keywords.add("insulated")
        if "wood" in name:
            keywords.add("wood")
        if "glass" in name or "glaz" in name:
            keywords.add("glass")
    return sorted(keywords)


def _material_phrase_from_keywords(keywords: List[str]) -> str:
    kws = set(keywords)
    if "glass" in kws and "metal" in kws:
        return "metal framed glass"
    if "glass" in kws:
        return "glass"
    if "metal" in kws and "insulated" in kws:
        return "insulated metal"
    if "metal" in kws:
        return "metal"
    if "wood" in kws:
        return "wood"
    if "insulated" in kws:
        return "insulated"
    return ""


def build_door_search_material_from_model(model) -> Optional[Dict[str, Any]]:
    doors = [ss for ss in model.getSubSurfaces()
             if ss.subSurfaceType() in ("Door", "GlassDoor", "OverheadDoor")]
    if not doors:
        return None

    default_door_construction = _get_default_exterior_door_construction(model)
    all_keywords = set()

    for door in doors:
        construction = None
        if door.construction().is_initialized():
            construction = door.construction().get()
        elif default_door_construction is not None:
            construction = default_door_construction

        if construction is not None:
            for kw in _collect_material_keywords_from_construction(construction):
                all_keywords.add(kw)

    dims = _estimate_door_dimensions_m(doors[0])
    if dims:
        width_ft_in = _format_feet_inches(dims["width_m"])
        height_ft_in = _format_feet_inches(dims["height_m"])
        size_str = f"{width_ft_in} x {height_ft_in}"
    else:
        size_str = "approx size unknown"

    material_phrase = _material_phrase_from_keywords(sorted(all_keywords))
    if material_phrase:
        search_term = f"{material_phrase} door {size_str}"
    else:
        search_term = f"door {size_str}"

    description = f"{len(doors)} door(s); materials: {', '.join(sorted(all_keywords)) or 'unspecified'}; size: {size_str}"

    return {
        "name": search_term.strip(),
        "description": description,
        "quantity": float(len(doors)),
        "unit": "ea",
        "division_code": "08",
    }


def extract_materials_from_model(model, feature_keys: Dict[str, str]) -> List[Dict[str, Any]]:
    materials: List[Dict[str, Any]] = []

    for obj in model.objects():
        if not hasattr(obj, "additionalProperties"):
            continue
        try:
            props = obj.additionalProperties()
        except Exception:
            continue

        if not props.featureNames() or not props.hasFeature(feature_keys["name"]):
            continue

        name = _get_feature_as_string(props, feature_keys["name"])
        if not name:
            continue

        quantity = _get_feature_as_float(props, feature_keys["quantity"]) or 1.0
        unit = _get_feature_as_string(props, feature_keys["unit"]) or ""
        description = _get_feature_as_string(props, feature_keys["description"]) or ""
        division_code = _get_feature_as_string(props, feature_keys["division_code"])
        unit_cost = _get_feature_as_float(props, feature_keys["unit_cost"])
        total_cost = _get_feature_as_float(props, feature_keys["total_cost"])

        material = {
            "name": name,
            "description": description,
            "quantity": quantity,
            "unit": unit,
            "division_code": division_code,
            "unit_cost": unit_cost,
            "total_cost": total_cost,
        }

        try:
            material["object_handle"] = obj.handle().__str__()
        except Exception:
            material["object_handle"] = None

        try:
            material["object_name"] = obj.nameString()
        except Exception:
            material["object_name"] = None

        materials.append(material)

    return materials


def extract_paths_from_apply_measure(script_dir: Path) -> tuple:
    """
    Parse apply_measure.py to find input and output model paths.
    
    Args:
        script_dir: Directory containing apply_measure.py (parent of resources/)
    
    Returns:
        tuple: (input_model_path, output_model_path)
    """
    apply_measure_path = script_dir / "apply_measure.py"
    
    if not apply_measure_path.exists():
        raise FileNotFoundError(f"apply_measure.py not found at {apply_measure_path}")
    
    with open(apply_measure_path, "r", encoding="utf-8") as f:
        content = f.read()
    
    # Look for: model_path = SCRIPT_DIR / "tests" / "DOE_small_office.osm"
    input_match = re.search(r'model_path\s*=\s*SCRIPT_DIR\s*/\s*"tests"\s*/\s*"([^"]+)"', content)
    if not input_match:
        raise ValueError("Could not find model_path in apply_measure.py")
    
    input_filename = input_match.group(1)
    input_path = script_dir / "tests" / input_filename
    
    # Look for: output_dir = SCRIPT_DIR / "tests" / "output"
    output_dir_match = re.search(r'output_dir\s*=\s*SCRIPT_DIR\s*/\s*"tests"\s*/\s*"([^"]+)"', content)
    if output_dir_match:
        output_subdir = output_dir_match.group(1)
        output_dir = script_dir / "tests" / output_subdir
    else:
        output_dir = script_dir / "tests" / "output"  # fallback
    
    # Look for: output_model_path = output_dir / "<enhanced_model>.osm"
    output_match = re.search(r'output_model_path\s*=\s*output_dir\s*/\s*"([^"]+)"', content)
    if not output_match:
        raise ValueError("Could not find output_model_path in apply_measure.py")
    
    output_filename = output_match.group(1)
    output_path = output_dir / output_filename
    
    return (input_path, output_path)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments for standalone usage."""
    
    # Determine script directory (parent of resources/ if running from resources/)
    script_file = Path(__file__).resolve()
    if script_file.parent.name == "resources":
        measure_dir = script_file.parent.parent
    else:
        measure_dir = script_file.parent
    
    # Try to extract default paths from apply_measure.py
    try:
        default_input, default_output_model = extract_paths_from_apply_measure(measure_dir)
        default_output_json = default_output_model.parent / "rsmeans_search_results.json"
        auto_detected = True
    except Exception:
        # Fallback to reasonable defaults
        default_output_model = measure_dir / "tests" / "output" / "model_enhanced.osm"
        default_output_json = measure_dir / "tests" / "output" / "rsmeans_search_results.json"
        auto_detected = False
    
    parser = argparse.ArgumentParser(
        description="RSMeans API lookup for materials stored in OpenStudio OSM files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Auto-detect paths from apply_measure.py and search multiple catalogs
  python resources/call_rsmeans_api.py
  
  # Search specific catalogs with 25%% overhead
  python resources/call_rsmeans_api.py --catalogs bc-mf,gb-mf,sq-mf --overhead-profit-percent 25
  
  # Use custom model path
  python resources/call_rsmeans_api.py --model path/to/model.osm
        """
    )
    
    help_text = "Path to OSM file"
    if auto_detected:
        help_text += " (default: auto-detected from apply_measure.py)"
    
    parser.add_argument("--model", default=str(default_output_model), help=help_text)
    parser.add_argument("--output", default=str(default_output_json), help="Path to save JSON results")
    parser.add_argument("--release", default="2024-an", help="RSMeans release ID (e.g., 2024-an)")
    parser.add_argument(
        "--catalogs",
        default="bc-mf,gb-mf,rp-mf",
        help="Comma-separated catalog codes (bc-mf, gb-mf, rp-mf, sq-mf, hc-mf, si-mf)"
    )
    parser.add_argument("--location", default="us-us-national", help="Location ID")
    parser.add_argument("--labor-type", default="std", help="Labor type (std, opn, fmr, fed, he)")
    parser.add_argument("--measurement-system", default="imp", help="Measurement system (imp, met)")
    parser.add_argument("--use-sandbox", action="store_true", help="Use RSMeans sandbox API")
    parser.add_argument(
        "--overhead-profit-percent",
        type=float,
        default=0.0,
        help="Percent applied to material cost for overhead+profit",
    )
    return parser.parse_args()


def main() -> int:
    """Main entry point when run as a standalone script."""
    args = parse_args()
    load_dotenv()

    client_id = os.getenv("client_id")
    client_secret = os.getenv("client_secret")

    if not client_id or not client_secret:
        print("ERROR: RSMeans API credentials not found.")
        print("Set environment variables: client_id, client_secret")
        print("Or create a .env file with these values.")
        return 1

    model_path = Path(args.model).resolve()
    if not model_path.exists():
        print(f"ERROR: Model file not found: {model_path}")
        return 1

    # Try multiple methods to extract materials
    materials = None
    model_dir = model_path.parent
    
    # Method 1: Pre-saved JSON file
    materials_file_candidates = [
        model_dir / "door_enhancement_retrofit_materials.json",
    ]
    for materials_file in materials_file_candidates:
        if materials_file.exists():
            try:
                with open(materials_file, "r", encoding="utf-8") as f:
                    materials = json.load(f)
                print(f"Extracted {len(materials)} materials from {materials_file.name}")
                break
            except Exception as e:
                print(f"Warning: Could not load materials file {materials_file.name}: {e}")
    
    # Method 2: Extract from model's Facility AdditionalProperties
    if not materials:
        print(f"Loading model from {model_path.name}...")
        model = load_openstudio_model(model_path)
        
        if model.facility().is_initialized():
            facility = model.facility().get()
            props = facility.additionalProperties()
            
            # Try door-specific serialized materials property.
            facility_json_feature_candidates = [
                "door_enhancement_retrofit_materials_json",
            ]
            for feature_name in facility_json_feature_candidates:
                if materials:
                    break
                if props.hasFeature(feature_name):
                    try:
                        opt_str = props.getFeatureAsString(feature_name)
                        if opt_str.is_initialized():
                            json_str = opt_str.get()
                            materials = json.loads(json_str)
                            print(f"Extracted {len(materials)} materials from Facility.{feature_name}")
                            break
                    except Exception as e:
                        print(f"Warning: Could not parse Facility.{feature_name}: {e}")
        
        # Method 3: Fall back to individual property extraction
        if not materials:
            materials = extract_materials_from_model(model, DEFAULT_FEATURE_KEYS)
            if materials:
                print(f"Extracted {len(materials)} materials using standard property keys")

        # Method 4: Derive a door-based search term from the model
        if not materials:
            derived = build_door_search_material_from_model(model)
            if derived:
                materials = [derived]
                print("Derived door-based RSMeans search term from model:")
                print(f"  Search term: {derived['name']}")
                print(f"  Details: {derived['description']}")

    if not materials:
        print("ERROR: No retrofit materials found in model.")
        print("The model must have materials stored in AdditionalProperties.")
        return 1

    # Parse catalog list
    catalogs = [c.strip() for c in args.catalogs.split(",")]
    print(f"\nSearching RSMeans catalogs: {', '.join(catalogs)}")
    
    # Authenticate
    client = RSMeansAPIClient(client_id, client_secret, use_sandbox=args.use_sandbox)
    if not client.authenticate():
        print("ERROR: Authentication failed.")
        return 1

    # Search across all catalogs
    print(f"Searching for {len(materials)} materials...")
    results = search_materials_across_catalogs(
        materials=materials,
        client=client,
        catalogs=catalogs,
        release_id=args.release,
        location_id=args.location,
        labor_type=args.labor_type,
        measurement_system=args.measurement_system,
    )

    # Calculate costs
    total_material_cost = float(results.get("total_cost", 0.0))
    # Per-line unit costs already include RSMeans O&P (``totalOpCost``); no
    # additional markup is applied.
    overhead_profit_cost = 0.0
    total_cost = total_material_cost

    # Prepare summary
    summary = {
        "total_material_cost": total_material_cost,
        "overhead_profit_percent": args.overhead_profit_percent,
        "total_overhead_profit_cost": overhead_profit_cost,
        "total_cost_with_overhead_profit": total_cost,
        "materials_count": len(results.get("materials", [])),
        "materials_searched": len(materials),
        "catalogs_searched": catalogs,
    }

    # Save results
    output_path = Path(args.output).resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    with output_path.open("w", encoding="utf-8") as f:
        json.dump({"summary": summary, "results": results}, f, indent=2)

    # Print summary
    print("\n" + "=" * 70)
    print("COST SUMMARY")
    print("=" * 70)
    print(f"Materials searched:  {len(materials)}")
    print(f"Materials matched:   {len(results.get('materials', []))}")
    print(f"Material cost:       ${total_material_cost:,.2f}")
    print(f"Overhead+profit:     ${overhead_profit_cost:,.2f} ({args.overhead_profit_percent}%)")
    print(f"TOTAL COST:          ${total_cost:,.2f}")
    print("=" * 70)
    
    if results.get("errors"):
        print(f"\nWarnings ({len(results['errors'])} items):")
        for error in results["errors"][:5]:
            print(f"  - {error}")
        if len(results["errors"]) > 5:
            print(f"  ... and {len(results['errors']) - 5} more")
    
    print(f"\nResults saved to: {output_path}")
    return 0


def search_materials_across_catalogs(
    materials: List[Dict[str, Any]],
    client: "RSMeansAPIClient",
    catalogs: Optional[List[str]] = None,
    release_id: str = "2024-an",
    location_id: str = "us-us-national",
    labor_type: str = "std",
    measurement_system: str = "imp",
) -> Dict[str, Any]:
    """Search for materials across multiple RSMeans catalogs and return best matches.

    For each material the function tries, in order:
    1. Exact user-supplied RSMeans ID (if ``explicit_rsmeans_id`` is set).
    2. Text search using ``generate_search_term_alternatives``, accepting the
       first candidate whose clamped score >= ``MIN_ACCEPTABLE_MATCH_SCORE``.
    3. Hard-coded fallback ID from ``_get_default_fallback_rsmeans_id`` if no
       search result passes the score threshold.
    
    Args:
        materials: List of material dicts with 'name', 'quantity', 'unit', etc.
        client: Authenticated RSMeansAPIClient instance
        catalogs: List of catalog codes to search (default: all common catalogs)
        release_id: RSMeans release ID (e.g., "2024-an")
        location_id: Location for pricing
        labor_type: Labor type code
        measurement_system: "imp" or "met"
    
    Returns:
        Dict with 'total_cost', 'materials' (with catalog info), 'errors', 'search_log'
    """
    if catalogs is None:
        # Default to common building-related catalogs
        catalogs = ["bc-mf", "gb-mf", "rp-mf"]  # Building Construction, Green Building, Repair & Remodeling
    
    all_results = []
    search_log = []
    errors = []
    warnings = []
    total_cost = 0.0
    total_material_cost_bare = 0.0
    total_labor_cost_bare = 0.0
    total_equipment_cost_bare = 0.0
    fallback_count = 0
    
    for material in materials:
        material_name = material.get("name", "unknown")
        quantity = material.get("quantity", 1.0)
        unit = material.get("unit", "")
        division_code = material.get("division_code")
        explicit_rsmeans_id = str(
            material.get("explicit_rsmeans_id")
            or material.get("rsmeans_unit_costline_id")
            or ""
        ).strip()

        print("\n" + "-" * 70)
        print(f"RSMeans lookup for material: {material_name}")
        print(f"Quantity: {quantity} {unit} | Division: {division_code or 'auto'}")
        
        best_match = None
        best_cost = None
        best_catalog = None
        matched_term = None
        best_source = "rsmeans_search"

        # Optional exact line-id override path (if user supplied one).
        if explicit_rsmeans_id:
            for catalog in catalogs:
                explicit_item = _lookup_cost_item_by_rsmeans_id(
                    client=client,
                    rsmeans_id=explicit_rsmeans_id,
                    catalog=catalog,
                    release_id=release_id,
                    location_id=location_id,
                    labor_type=labor_type,
                    measurement_system=measurement_system,
                )
                if explicit_item:
                    unit_cost = float(explicit_item.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0)
                    line_uom = explicit_item.get("unitOfMeasure", "")
                    line_id = explicit_item.get("id", explicit_rsmeans_id)
                    if unit_cost > 0 and division_code and not _id_matches_division(line_id, division_code):
                        warnings.append(
                            f"User-provided RSMeans ID {explicit_rsmeans_id} for '{material_name}' "
                            f"resolved to id '{line_id}' which is outside requested division '{division_code}'. "
                            f"Rejecting to avoid cross-division contamination."
                        )
                        unit_cost = 0.0
                    if unit_cost > 0 and not _uom_compatible(unit, line_uom):
                        warnings.append(
                            f"User-provided RSMeans ID {explicit_rsmeans_id} for '{material_name}' "
                            f"has UOM '{line_uom}' which is incompatible with requested unit '{unit}'. "
                            f"Rejecting this match to avoid unit-mismatch costing errors."
                        )
                        unit_cost = 0.0
                    if unit_cost > 0:
                        total = unit_cost * quantity
                        _split = _split_total_by_bare(explicit_item, total)
                        all_results.append({
                            **material,
                            "catalog": catalog,
                            "search_term_used": "user_rsmeans_id",
                            "unit_cost": unit_cost,
                            "total_cost": total,
                            "total_material_cost": _split["material"],
                            "total_labor_cost": _split["labor"],
                            "total_equipment_cost": _split["equipment"],
                            "bare_material_unit_cost": (float(_split["material"] or 0.0) / float(quantity or 1.0)) if float(quantity or 0.0) > 0.0 else 0.0,
                            "bare_material_unit_basis": line_uom,
                            "cost_component_source": _split["source"],
                            "rsmeans_id": explicit_item.get("id", explicit_rsmeans_id),
                            "rsmeans_description": explicit_item.get("description", ""),
                            "rsmeans_unit_of_measure": line_uom,
                            "source": "rsmeans_user_id",
                            "match_type": "exact_id_match",
                            "chosen_source_type": "user_id",
                        })
                        _append_rsmeans_raw_log(material, explicit_item, catalog, "explicit_id_match", "user_rsmeans_id")
                        total_cost += total
                        total_material_cost_bare += _split["material"]
                        total_labor_cost_bare += _split["labor"]
                        total_equipment_cost_bare += _split["equipment"]
                        search_log.append({
                            "material": material_name,
                            "status": "explicit_id_match",
                            "explicit_rsmeans_id": explicit_rsmeans_id,
                            "catalog": catalog,
                            "unit_cost": unit_cost,
                            "unit_of_measure": line_uom,
                            "quantity": quantity,
                            "total_cost": total,
                        })
                        best_match = explicit_item
                        break

            if best_match:
                continue

            warnings.append(
                f"User-provided RSMeans ID {explicit_rsmeans_id} was not found; falling back to search logic for '{material_name}'"
            )

        # Forced fallback path for configured seal/door options.
        forced_fallback_id = _get_forced_fallback_rsmeans_id(
            material_name,
            material.get("description", ""),
        )
        if forced_fallback_id:
            forced_item = None
            forced_catalog = None
            for catalog in catalogs:
                forced_item = _lookup_cost_item_by_rsmeans_id(
                    client=client,
                    rsmeans_id=forced_fallback_id,
                    catalog=catalog,
                    release_id=release_id,
                    location_id=location_id,
                    labor_type=labor_type,
                    measurement_system=measurement_system,
                )
                if forced_item:
                    forced_catalog = catalog
                    break

            if forced_item:
                unit_cost = float(forced_item.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0)
                line_uom = forced_item.get("unitOfMeasure", "")
                line_id = forced_item.get("id", forced_fallback_id)
                if unit_cost > 0 and division_code and not _id_matches_division(line_id, division_code):
                    warnings.append(
                        f"Forced RSMeans ID {forced_fallback_id} for '{material_name}' "
                        f"resolved to id '{line_id}' outside division '{division_code}'. "
                        f"Falling back to search logic."
                    )
                    unit_cost = 0.0
                if unit_cost > 0 and not _uom_compatible(unit, line_uom):
                    warnings.append(
                        f"Forced RSMeans ID {forced_fallback_id} for '{material_name}' "
                        f"has UOM '{line_uom}' incompatible with requested unit '{unit}'. "
                        f"Falling back to search logic."
                    )
                    unit_cost = 0.0

                if unit_cost > 0:
                    total = unit_cost * quantity
                    _split = _split_total_by_bare(forced_item, total)
                    all_results.append({
                        **material,
                        "catalog": forced_catalog,
                        "search_term_used": "forced_fallback_rsmeans_id",
                        "unit_cost": unit_cost,
                        "total_cost": total,
                        "total_material_cost": _split["material"],
                        "total_labor_cost": _split["labor"],
                        "total_equipment_cost": _split["equipment"],
                        "bare_material_unit_cost": (float(_split["material"] or 0.0) / float(quantity or 1.0)) if float(quantity or 0.0) > 0.0 else 0.0,
                        "bare_material_unit_basis": line_uom,
                        "cost_component_source": _split["source"],
                        "rsmeans_id": line_id,
                        "rsmeans_description": forced_item.get("description", ""),
                        "rsmeans_unit_of_measure": line_uom,
                        "source": "rsmeans_forced_fallback_id",
                        "match_type": "forced_fallback_id",
                        "chosen_source_type": "forced_fallback",
                    })
                    _append_rsmeans_raw_log(
                        material,
                        forced_item,
                        forced_catalog,
                        "forced_fallback_rsmeans_id",
                        "forced_fallback_rsmeans_id",
                    )
                    total_cost += total
                    total_material_cost_bare += _split["material"]
                    total_labor_cost_bare += _split["labor"]
                    total_equipment_cost_bare += _split["equipment"]
                    fallback_count += 1
                    search_log.append({
                        "material": material_name,
                        "status": "forced_fallback_match",
                        "forced_rsmeans_id": forced_fallback_id,
                        "catalog": forced_catalog,
                        "unit_cost": unit_cost,
                        "unit_of_measure": line_uom,
                        "quantity": quantity,
                        "total_cost": total,
                    })
                    continue
                warnings.append(
                    f"Forced RSMeans ID {forced_fallback_id} for '{material_name}' was found but unusable; falling back to search logic."
                )
            else:
                warnings.append(
                    f"Forced RSMeans ID {forced_fallback_id} for '{material_name}' was not found; falling back to search logic."
                )
        
        # Generate alternative search terms
        search_alternatives = generate_search_term_alternatives(material_name)
        
        # If we have a division code from material properties, prioritize it
        if division_code:
            search_alternatives.insert(0, (material_name, division_code))
        
        # Try each catalog with intelligent search term alternatives
        for catalog in catalogs:
            if best_match:
                break  # Already found a match in a previous catalog
            
            # Try alternative search terms within this catalog
            for alt_term, alt_division in search_alternatives:
                try:
                    print(f"  • Searching '{alt_term}' (div {alt_division or 'any'}) in {catalog}")
                    results = client.search_unit_costlines(
                        search_term=alt_term,
                        division_code=alt_division,
                        catalog=catalog,
                        release_id=release_id,
                        location_id=location_id,
                        labor_type=labor_type,
                        measurement_system=measurement_system,
                    )
                    
                    items = _filter_demo_items(_extract_search_items(results))
                    if items:
                        match, ranked_candidates = _select_best_rsmeans_candidate(
                            material_name,
                            items,
                            material,
                        )
                        if not match:
                            continue
                        division_id = match.get("id", "")
                        _candidate_count = len(ranked_candidates or [])
                        _force_fallback_multi = False
                        if not explicit_rsmeans_id and _candidate_count > 1:
                            _fallback_id = _get_default_fallback_rsmeans_id(
                                material_name,
                                material.get("description", ""),
                            )
                            if _fallback_id:
                                division_id = _fallback_id
                                _force_fallback_multi = True
                                search_log.append({
                                    "material": material_name,
                                    "search_term": alt_term,
                                    "catalog": catalog,
                                    "division": alt_division,
                                    "status": "multi_candidate_fallback",
                                    "forced_fallback_costline_id": division_id,
                                    "candidate_scores": ranked_candidates[:5],
                                })
                        print(f"    ✓ Match: {match.get('description', '')} (id {division_id})")
                        
                        # Get detailed cost data
                        cost_line = client.get_unit_costlines(
                            release_id=release_id,
                            catalog=catalog,
                            location_id=location_id,
                            labor_type=labor_type,
                            measurement_system=measurement_system,
                            division_code=division_id,
                        )
                        
                        if cost_line and "items" in cost_line:
                            for item in cost_line["items"]:
                                if item.get("id") == division_id:
                                    unit_cost = float(item.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0)
                                    line_uom = item.get("unitOfMeasure", "")
                                    if unit_cost > 0 and division_code and not _id_matches_division(division_id, division_code):
                                        search_log.append({
                                            "material": material_name,
                                            "search_term": alt_term,
                                            "catalog": catalog,
                                            "division": alt_division,
                                            "status": "division_mismatch",
                                            "requested_division": division_code,
                                            "rsmeans_id": division_id,
                                            "rsmeans_description": item.get("description", ""),
                                        })
                                        unit_cost = 0.0
                                    if unit_cost > 0 and not _uom_compatible(unit, line_uom):
                                        # Reject: skip this candidate and keep searching.
                                        search_log.append({
                                            "material": material_name,
                                            "search_term": alt_term,
                                            "catalog": catalog,
                                            "division": alt_division,
                                            "status": "uom_incompatible",
                                            "unit_of_measure": line_uom,
                                            "requested_unit": unit,
                                            "rsmeans_id": division_id,
                                            "rsmeans_description": item.get("description", ""),
                                        })
                                        unit_cost = 0.0
                                    if unit_cost > 0:
                                        best_match = item
                                        best_cost = unit_cost * quantity
                                        best_catalog = catalog
                                        if _force_fallback_multi or match.get("is_fallback"):
                                            matched_term = "fallback_rsmeans_id"
                                            best_source = "rsmeans_fallback_id"
                                        else:
                                            matched_term = alt_term
                                            best_source = "rsmeans_search"
                                        
                                        status_msg = f"match_found"
                                        if alt_term != material_name:
                                            status_msg += f" (using '{alt_term}')"
                                            print(f"  -> Found match using alternative term: '{alt_term}' in catalog {catalog}")
                                        
                                        search_log.append({
                                            "material": material_name,
                                            "search_term": alt_term,
                                            "catalog": catalog,
                                            "division": alt_division,
                                            "status": status_msg,
                                            "unit_cost": unit_cost,
                                            "unit_of_measure": line_uom,
                                            "quantity": quantity,
                                            "total_cost": best_cost,
                                            "candidate_scores": ranked_candidates[:5],
                                        })
                                        break
                            
                            if best_match:
                                break  # Exit alternative terms loop
                    
                except Exception as e:
                    search_log.append({
                        "material": material_name,
                        "search_term": alt_term,
                        "catalog": catalog,
                        "status": "error",
                        "error": str(e)
                    })
        
        if best_match:
            _split = _split_total_by_bare(best_match, float(best_cost or 0.0))
            _qty = float(quantity or 0.0)
            _bare_unit = (float(_split["material"] or 0.0) / _qty) if _qty > 0.0 else 0.0
            _raw_comp = _extract_bare_components(best_match)
            _raw_unit_cost = float(_raw_comp.get("material", 0.0) or 0.0) + float(_raw_comp.get("labor", 0.0) or 0.0) + float(_raw_comp.get("equipment", 0.0) or 0.0)
            _raw_uom = _normalize_uom(best_match.get("unitOfMeasure", ""))
            if _raw_unit_cost <= 0.0:
                _raw_unit_cost = float(best_match.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0)
            if not _raw_uom:
                _raw_uom = str(best_match.get("unitOfMeasure", "") or "")
            material_result = {
                **material,
                "catalog": best_catalog,
                "search_term_used": matched_term,
                "unit_cost": best_match.get("localizedCosts", {}).get("totalOpCost", 0.0),
                "total_cost": best_cost,
                "rsmeans_id": best_match.get("id", ""),
                "rsmeans_description": best_match.get("description", ""),
                "rsmeans_unit_of_measure": best_match.get("unitOfMeasure", ""),
                "source": best_source,
                "match_type": "fallback_id" if best_source == "rsmeans_fallback_id" else "closest_match",
                "chosen_source_type": "fallback" if best_source == "rsmeans_fallback_id" else "search",
                "bare_material_unit_cost": _bare_unit,
                "bare_material_unit_basis": best_match.get("unitOfMeasure", ""),
                "pricing_unit_cost_raw": _raw_unit_cost,
                "pricing_unit_uom_raw": _raw_uom,
                "pricing_unit_cost_effective": float(best_match.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0),
                "pricing_unit_uom_effective": _raw_uom,
                "pricing_source": "rsmeans_direct" if float(best_match.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0) > 0.0 else "unavailable",
            }
            material_result["total_material_cost"] = _split["material"]
            material_result["total_labor_cost"] = _split["labor"]
            material_result["total_equipment_cost"] = _split["equipment"]
            material_result["cost_component_source"] = _split["source"]
            all_results.append(material_result)
            _append_rsmeans_raw_log(material, best_match, best_catalog, str(best_source or "search"), matched_term)
            total_cost += best_cost
            total_material_cost_bare += _split["material"]
            total_labor_cost_bare += _split["labor"]
            total_equipment_cost_bare += _split["equipment"]
            if best_source == "rsmeans_fallback_id":
                fallback_count += 1
                warnings.append(
                    f"Used fallback RSMeans ID {best_match.get('id', '')} for '{material_name}' due to candidate score bounds"
                )
        else:
            fallback_id = _get_default_fallback_rsmeans_id(
                material_name,
                material.get("description", ""),
            )
            fallback_item = None
            fallback_catalog = None

            if fallback_id:
                for catalog in catalogs:
                    fallback_item = _lookup_cost_item_by_rsmeans_id(
                        client=client,
                        rsmeans_id=fallback_id,
                        catalog=catalog,
                        release_id=release_id,
                        location_id=location_id,
                        labor_type=labor_type,
                        measurement_system=measurement_system,
                    )
                    if fallback_item:
                        fallback_catalog = catalog
                        break

            if fallback_item:
                unit_cost = float(fallback_item.get("localizedCosts", {}).get("totalOpCost", 0.0) or 0.0)
                line_uom = fallback_item.get("unitOfMeasure", "")
                line_id = fallback_item.get("id", fallback_id)
                if unit_cost > 0 and division_code and not _id_matches_division(line_id, division_code):
                    warnings.append(
                        f"Final fallback RSMeans ID {fallback_id} for '{material_name}' "
                        f"resolved to id '{line_id}' outside division '{division_code}'. Skipping."
                    )
                    errors.append(
                        f"No division-compatible RSMeans match found for: {material_name} (division {division_code})"
                    )
                    search_log.append({
                        "material": material_name,
                        "status": "fallback_division_mismatch",
                        "fallback_rsmeans_id": fallback_id,
                        "catalog": fallback_catalog,
                        "requested_division": division_code,
                    })
                    continue
                if unit_cost > 0 and not _uom_compatible(unit, line_uom):
                    warnings.append(
                        f"Final fallback RSMeans ID {fallback_id} for '{material_name}' "
                        f"has UOM '{line_uom}' incompatible with requested unit '{unit}'. "
                        f"Skipping cost assignment to avoid unit-mismatch errors."
                    )
                    errors.append(
                        f"No UOM-compatible RSMeans match found for: {material_name} (requested {unit})"
                    )
                    search_log.append({
                        "material": material_name,
                        "status": "fallback_uom_incompatible",
                        "fallback_rsmeans_id": fallback_id,
                        "catalog": fallback_catalog,
                        "unit_of_measure": line_uom,
                        "requested_unit": unit,
                    })
                    continue
                total = unit_cost * quantity
                _split = _split_total_by_bare(fallback_item, total)
                all_results.append({
                    **material,
                    "catalog": fallback_catalog,
                    "search_term_used": "fallback_rsmeans_id",
                    "unit_cost": unit_cost,
                    "total_cost": total,
                    "total_material_cost": _split["material"],
                    "total_labor_cost": _split["labor"],
                    "total_equipment_cost": _split["equipment"],
                    "bare_material_unit_cost": (float(_split["material"] or 0.0) / float(quantity or 1.0)) if float(quantity or 0.0) > 0.0 else 0.0,
                    "bare_material_unit_basis": line_uom,
                    "cost_component_source": _split["source"],
                    "rsmeans_id": fallback_item.get("id", fallback_id),
                    "rsmeans_description": fallback_item.get("description", ""),
                    "rsmeans_unit_of_measure": line_uom,
                    "source": "rsmeans_fallback_id",
                    "match_type": "fallback_id",
                    "chosen_source_type": "fallback",
                })
                _append_rsmeans_raw_log(material, fallback_item, fallback_catalog, "fallback_rsmeans_id", "fallback_rsmeans_id")
                total_cost += total
                total_material_cost_bare += _split["material"]
                total_labor_cost_bare += _split["labor"]
                total_equipment_cost_bare += _split["equipment"]
                fallback_count += 1
                warning_message = (
                    f"Used fallback RSMeans ID {fallback_id} for '{material_name}' "
                    f"after no direct search match"
                )
                warnings.append(warning_message)
                search_log.append({
                    "material": material_name,
                    "status": "fallback_match",
                    "fallback_rsmeans_id": fallback_id,
                    "catalog": fallback_catalog,
                    "unit_cost": unit_cost,
                    "unit_of_measure": line_uom,
                    "quantity": quantity,
                    "total_cost": total,
                })
            else:
                errors.append(f"No RSMeans match found in any catalog for: {material_name}")
                search_log.append({
                    "material": material_name,
                    "status": "no_match",
                    "catalogs_searched": catalogs,
                    "alternatives_tried": len(search_alternatives),
                    "fallback_rsmeans_id": fallback_id,
                })
    
    return {
        "total_cost": total_cost,
        "total_material_cost": total_material_cost_bare,
        "total_labor_cost": total_labor_cost_bare,
        "total_equipment_cost": total_equipment_cost_bare,
        "materials": all_results,
        "errors": errors,
        "warnings": warnings,
        "fallback_count": fallback_count,
        "search_log": search_log,
        "catalogs_searched": catalogs
    }


def run_rsmeans_cost_lookup(
    materials: List[Dict[str, Any]],
    release_id: str = "2024-an",
    catalogs: Optional[List[str]] = None,
    location_id: str = "us-us-national",
    labor_type: str = "std",
    measurement_system: str = "imp",
    use_sandbox: bool = False,
    overhead_profit_percent: float = 0.0,
) -> Dict[str, Any]:
    """Run RSMeans lookup for provided materials and return summary/results."""
    load_dotenv()
    client_id = os.getenv("client_id")
    client_secret = os.getenv("client_secret")

    if not client_id or not client_secret:
        append_measure_summary_record(MEASURE_LOG_SLUG, {
            "status": "auth_error",
            "message": "RSMeans API credentials not found in environment",
        })
        return {
            "status": "auth_error",
            "message": "RSMeans API credentials not found in environment",
        }

    client = RSMeansAPIClient(client_id, client_secret, use_sandbox=use_sandbox)
    if not client.authenticate():
        append_measure_summary_record(MEASURE_LOG_SLUG, {
            "status": "auth_error",
            "message": "RSMeans authentication failed",
        })
        return {
            "status": "auth_error",
            "message": "RSMeans authentication failed",
        }

    results = search_materials_across_catalogs(
        materials=materials,
        client=client,
        catalogs=catalogs,
        release_id=release_id,
        location_id=location_id,
        labor_type=labor_type,
        measurement_system=measurement_system,
    )

    total_material_cost = float(results.get("total_material_cost", 0.0))
    total_labor_cost = float(results.get("total_labor_cost", 0.0))
    total_equipment_cost = float(results.get("total_equipment_cost", 0.0))
    total_bare_cost = total_material_cost + total_labor_cost + total_equipment_cost
    if total_bare_cost <= 0.0:
        total_bare_cost = float(results.get("total_cost", 0.0))
        total_material_cost = total_bare_cost
    # The per-line unit cost used during aggregation is the RSMeans
    # ``totalOpCost`` (Total Incl. O&P), so no additional overhead/profit
    # markup is applied here. The ``overhead_profit_percent`` argument is
    # retained for backward compatibility and is recorded in the summary
    # only; it does not alter the reported total.
    overhead_profit_cost = 0.0
    total_cost = total_bare_cost

    summary = {
        "total_material_cost": total_material_cost,
        "total_labor_cost": total_labor_cost,
        "total_equipment_cost": total_equipment_cost,
        "total_bare_cost": total_bare_cost,
        "overhead_profit_percent": overhead_profit_percent,
        "total_overhead_profit_cost": overhead_profit_cost,
        "total_cost_with_overhead_profit": total_cost,
        "materials_count": len(results.get("materials", [])),
        "materials_searched": len(materials),
        "catalogs_searched": results.get("catalogs_searched", catalogs or []),
        "release_id": release_id,
        "location_id": location_id,
        "labor_type": labor_type,
        "measurement_system": measurement_system,
        "use_sandbox": use_sandbox,
    }

    append_measure_summary_record(MEASURE_LOG_SLUG, {
        "status": "ok",
        "summary": summary,
        "results": results,
    })

    return {
        "status": "ok",
        "summary": summary,
        "results": results,
    }


if __name__ == "__main__":
    raise SystemExit(main())
